apiVersion: apps/v1
kind: Deployment
metadata:
  name: mecanicaos-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mecanicaos-api
  template:
    metadata:
      labels:
        app: mecanicaos-api
    spec:
      containers:
        - name: api
          image: mecanicaos-api:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: ConnectionStrings__DefaultConnection
              value: "Host=mecanicaos-db;Port=5432;Database=mecanicaos;Username=postgres;Password=postgres;Timeout=60;Command Timeout=60;Keepalive=60;Pooling=true;Minimum Pool Size=1;Maximum Pool Size=100;Connection Lifetime=300;"