apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-pod
spec:
  selector:
    app: api-pod
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080