apiVersion: v1
kind: ConfigMap
metadata:
    name: api-configmap
data:
    ASPNETCORE_ENVIRONMENT: Development
    ConnectionStrings__DefaultConnection: Host=db-service;Port=5432;Database=mecanicaos;Username=postgres;Password=postgres;Timeout=60;Command Timeout=60;Timeout=60;Keepalive=60;Pooling=true;Minimum Pool Size=1;Maximum Pool Size=100;Connection Lifetime=300;
    ASPNETCORE_URLS: http://+:80