apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-pod
  template:
    metadata:
      labels:
        app: api-pod
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:16-alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Aguardando a inicialização do banco de dados..."
              until PGPASSWORD=postgres psql -h db-service -U postgres -d mecanicaos -c 'SELECT 1' > /dev/null 2>&1; do
                echo "Aguardando o PostgreSQL ficar disponível...";
                sleep 2;
              done
              echo "Banco de dados disponível!"
        - name: run-migrations
          image: fthalita91/techchallenge-api:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Executando migrações..."
              dotnet ef database update --project /src/MecanicaOS/Infraestrutura/Infraestrutura.csproj --startup-project /src/MecanicaOS/API/API.csproj
              echo "Migrações concluídas."
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: ConnectionStrings__DefaultConnection
            - name: ASPNETCORE_URLS
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: ASPNETCORE_URLS
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: ASPNETCORE_ENVIRONMENT
      containers:
        - name: api
          image: fthalita91/techchallenge-api:latest
          ports:
            - containerPort: 80
          env:
            - name: SENDGRID_APIKEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: sendgrid_apikey
            - name: ASPNETCORE_URLS
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: ASPNETCORE_URLS
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: ASPNETCORE_ENVIRONMENT
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: ConnectionStrings__DefaultConnection

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-pod
spec:
  selector:
    app: api-pod
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080