apiVersion: apps/v1
kind: Deployment
metadata:
  name: mecanicaos-api
  labels:
    app: mecanicaos-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mecanicaos-api
  template:
    metadata:
      labels:
        app: mecanicaos-api
    spec:
      containers:
      - name: mecanicaos-api
        image: ghcr.io/felipeorlando/mecanica-os/mecanicaos-api:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: mecanicaos-api-config
        - secretRef:
            name: mecanicaos-api-secret
