apiVersion: apps/v1
kind: Deployment
metadata:
  name: mecanicaos-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mecanicaos-db
  template:
    metadata:
      labels:
        app: mecanicaos-db
    spec:
      containers:
        - name: db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: "mecanicaos"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}