name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get_sha.outputs.sha }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Obter o SHA do commit
        id: get_sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Construir e enviar a imagem Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/mecanicaos-api:${{ steps.get_sha.outputs.sha }}
            ${{ secrets.DOCKER_USERNAME }}/mecanicaos-api:latest

  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar o kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Atualizar a tag da imagem no manifesto de deploy
        run: |
          echo "A nova tag da imagem é: ${{ needs.build-and-push.outputs.image_tag }}"
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/mecanicaos-api:${{ needs.build-and-push.outputs.image_tag }}|g" k8s/api-deployment.yaml
          echo "Manifesto de deploy da API atualizado:"
          cat k8s/api-deployment.yaml

      - name: Aplicar todos os manifestos K8s
        run: |
          echo "Aplicando todos os manifestos da pasta k8s..."
          kubectl apply -f k8s/

      - name: Verificar o status do deploy
        run: |
          echo "Aguardando o deploy da API ser finalizado..."
          kubectl rollout status deployment/mecanicaos-api
          echo "Verificando os recursos criados..."
          kubectl get pvc
          kubectl get deployments
          kubectl get services
          kubectl get pods
          kubectl get configmap
          kubectl get secrets
          kubectl get hpa
