name: .NET

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore MecanicaOS.sln
    - name: Build
      run: dotnet build MecanicaOS.sln --no-restore
    - name: Test
      run: |
        chmod +x .github/scripts/check_test_success.sh
        .github/scripts/check_test_success.sh

  lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  create_pr:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: new feature"
          title: "PR for feature branch"
          body: "This PR was auto-generated."
          branch: ${{ github.ref }}
          base: main
